exclude:
  - node_modules
  - script

sass:
  style: :compressed

#theme: theme-2022
remote_theme: deargle-classes/theme-2022

title: BAIM4250 Spring 2022
description: Content for CU Boulder class BAIM4250 Spring 2022
